package dk.statsbiblioteket.doms.transformers.shardmigrator;

import dk.statsbiblioteket.doms.transformers.shardmigrator.dc.autogenerated.OaiDcType;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import java.io.StringReader;

/**
 * Created with IntelliJ IDEA.
 * User: kfc
 * Date: 10/19/12
 * Time: 1:45 PM
 * To change this template use File | Settings | File Templates.
 */
public class DCReader {
    public OaiDcType readDC(String dcOriginal) throws JAXBException {
        Unmarshaller oaiDcUnmarshaller = JAXBContext.newInstance(OaiDcType.class).createUnmarshaller();
        return ((JAXBElement<OaiDcType>) (oaiDcUnmarshaller.unmarshal(new StringReader(dcOriginal)))).getValue();
    }
}
