package dk.statsbiblioteket.doms.transformers.fileenricher;

import dk.statsbiblioteket.doms.central.CentralWebservice;
import dk.statsbiblioteket.doms.transformers.common.DomsConfig;
import dk.statsbiblioteket.doms.transformers.common.ObjectHandler;
import dk.statsbiblioteket.doms.transformers.fileenricher.autogenerated.BroadcastFileDescriptiveMetadataType;

/**
 * Use DOMS to enrich file metadata.
 */
public class DomsFileEnricherObjectHandler implements ObjectHandler {

    private final DomsConfig config;
    private final CentralWebservice webservice;

    /**
     * Initialise object handler.
     * @param config Configuration.
     * @param webservice The DOMS WebService.
     */
    public DomsFileEnricherObjectHandler(DomsConfig config, CentralWebservice webservice) {
        this.config = config;
        this.webservice = webservice;
    }

    @Override
    public void transform(String uuid) throws Exception {
        //TODO Use metadata in file name and from channel mapping database to update file object metadata.
        throw new UnsupportedOperationException("Not implemented yet");
    }


    private BroadcastFileDescriptiveMetadataType decodeFilename(String filename){
        return null;
    }

    private BroadcastFileDescriptiveMetadataType decodeMuxFilename(String filename){
        //mux1.1287514800-2010-10-19-21.00.00_1287518400-2010-10-19-22.00.00_dvb1-1.ts
        //(type).(timestart)-(timestart)_(timeend)-(timeEnd)_(recorder).ts
        return null;
    }

    private BroadcastFileDescriptiveMetadataType decodeRadioFilename(String filename){
        //drp1_88.100_DR-P1_pcm_20080509045602_20080510045501_encoder5-2.wav
        //(channelID)_(frequency)_(CHANNELID)_(format)_(timeStart)_(timeEnd)_(recorder).wav
        return null;

    }

    private BroadcastFileDescriptiveMetadataType decodeMpegFilename(String filename){
        //tv2c_623.250_K40-TV2-Charlie_mpeg1_20080503121001_20080504030601_encoder3-2.mpeg
        //kanal4_359.250_K42-Kanal4_mpeg1_20101023195601_20101023231601_encoder7-2.mpeg
        //tv3_161.250_S09-TV3_mpeg1_20101021175601_20101022010602_encoder6-2.mpeg
        //(channelID)_(frequency)_(CHANNELID)_(format)_(timeStart)_(timeEnd)_(recorder).mpeg
        return null;
    }

}
