package dk.statsbiblioteket.doms.transformers.fileenricher;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import dk.statsbiblioteket.doms.transformers.fileenricher.autogenerated.BroadcastFileDescriptiveMetadataType;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

/**
 * Created by IntelliJ IDEA.
 * User: abr
 * Date: 7/17/12
 * Time: 12:42 PM
 * To change this template use File | Settings | File Templates.
 */
public class DomsFileEnricherObjectHandlerTest {
    private String testMuxFileName = "mux1.1287514800-2010-10-19-21.00.00_1287518400-2010-10-19-22.00.00_dvb1-1.ts";
    private String testMuxStartTime = "1287514800";
    private String testMuxStopTime = "1287518400";
    private String testMuxRecoder = "dvb1-1";
    
    DomsFileEnricherObjectHandler handler;
    
    @Before
    public void setUp() throws Exception {
        handler = new DomsFileEnricherObjectHandler(null, null);
    }

    @After
    public void tearDown() throws Exception {

    }

    @Test
    public void testTransform() throws Exception {
        BroadcastFileDescriptiveMetadataType metadata = handler.decodeFilename(testMuxFileName);
        assertThat(metadata.getRecorder(), is(testMuxRecoder));
        assertThat(metadata.getStartTimeDate(), is(CalendarUtils.getXmlGregorianCalendar(testMuxStartTime)));
        assertThat(metadata.getEndTimeDate(), is(CalendarUtils.getXmlGregorianCalendar(testMuxStopTime)));
        
    }
}
