package dk.statsbiblioteket.doms.transformers.fileobjectcreator;

import dk.statsbiblioteket.doms.transformers.common.autogenerated.Channel;
import org.junit.Before;
import org.junit.Test;

import java.io.InputStream;
import java.util.Date;
import java.util.List;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertThat;
import static org.junit.Assert.assertTrue;

/**
 * Created by IntelliJ IDEA.
 * User: abr
 * Date: 7/17/12
 * Time: 4:56 PM
 * To change this template use File | Settings | File Templates.
 */
public class MuxFileChannelCalculatorTest {
    @Before
    public void setUp() throws Exception {

    }

    @Test
    public void testGetChannelIDsForMux() throws Exception {
        InputStream channelStream = Thread.currentThread().getContextClassLoader().getResourceAsStream("muxChannels.csv");
        MuxFileChannelCalculator calc = new MuxFileChannelCalculator(channelStream);


        List<Channel> channelIDs1 = calc.getChannelIDsForMux(1, new Date());
        assertThat(channelIDs1.size(), is(5));

        boolean success1 = false;
        for (Channel channel : channelIDs1) {
            if (channel.getChannelID().equals("dr1")) {
                success1 = true;
                break;
            }
        }
        assertTrue(success1);


        List<Channel> channelIDs2 = calc.getChannelIDsForMux(2, new Date());
        assertThat(channelIDs2.size(), is(5));

        boolean success2 = false;
        for (Channel channel : channelIDs2) {
            if (channel.getChannelID().equals("dr1")) {
                success2 = true;
                break;
            }
        }
        assertFalse(success2);
    }
}
