package dk.statsbiblioteket.doms.transformers.objectcreator;

import dk.statsbiblioteket.doms.transformers.common.FileNameParser;
import dk.statsbiblioteket.doms.transformers.common.autogenerated.BroadcastFileDescriptiveMetadataType;
import dk.statsbiblioteket.doms.transformers.common.muxchannels.MuxFileChannelCalculator;

import java.text.ParseException;
import java.util.Map;

public class DomsObject {
    public static final String BASE_URL = "http://bitfinder.statsbiblioteket.dk/bart/";

    private String fileName;
    private String checksum;
    private BroadcastFileDescriptiveMetadataType metadata;

    public DomsObject(String fileName,
                      String checksum,
                      Map<String, String> checksums,
                      MuxFileChannelCalculator muxFileChannelCalculator)
            throws ParseException {

        this.fileName = fileName;
        this.checksum = checksum;
        metadata = FileNameParser.decodeFilename(this.fileName, checksums, muxFileChannelCalculator);
    }

    public String toString() {
        return String.format(
                "%s <file:%s, checksum:%s, format:%s>",
                getClass().getName(),
                getFileName(),
                getChecksum(),
                getFormat()
        );
    }

    public String getFileName() {
        return fileName;
    }

    public String getChecksum() {
        return checksum;
    }

    public String getPermanentUrl() {
        return BASE_URL + fileName;
    }

    public String getFormat() {
        return metadata.getFormat();
    }
}
